### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by zdolny** [nescomtm/zad_82#1]
- [x] w html usun komentarz i dodaj doctype
- [x] usun pliki package.json i Gruntfile.js - tutaj sa niepotrzebne
- [x] zmien kodowanie pliku js na `utf-8` - https://scr.hu/RNk25a

**Comment by nescomtm** [comment]
zmieniłem plik index.html, błąd kodowanie wynikał z użytego edytora a mianowicie visual studio code podczas edycji pliku miał błędne kodowania.
usunięte zbędne pliki.

**Comment by zdolny** [comment]
teraz jeszcze dwie rzeczy:
- [ ] ujednolic wciecia w html
- [ ] usun niepotrzebne dolaczanie styli z head'a w html'u

**Comment by nescomtm** [comment]
zrobione ...

**Comment by zdolny** [comment]
dorzucilem poprawe wciec - teraz jest ok
